color: true
dry-run: null
hookfiles: ./bin/dredd/dredd_hook.rb
language: ruby
require: null
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: error
path: []
hooks-worker-timeout: 20000
hooks-worker-connect-timeout: 20000
hooks-worker-connect-retry: 2000
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: openapi2.yml
endpoint: 'http://localhost:3000'